name: Deploy to adv dev environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy viewer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replacements
        run: |
          sed -i 's/bkgAppId: \'\'/bkgAppId: \'${{ secrets.BKG_APP_ID }}\'/g' ./src/environments/environments.ts
      - name: Salus Scan
        id: salus_scan
        uses: federacy/scan-action@0.1.4
      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true" --log-level=debug
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install
        run: npm install
      - name: Audit packages
        run: npm audit
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Build
        run: npm run build-adv-dev
      - name: Rename deployment
        run: mv dist/basemap-viewer ./basemap-viewer
      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ADV_DEV_HOST }}
          username: ${{ secrets.ADV_DEV_USER }}
          password: ${{ secrets.ADV_DEV_PASS }}
          source: ./basemap-viewer
          target: ${{ secrets.ADV_DEV_PATH }}
